version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:            
      - /home/ubuntu/project/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/project/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
