services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Adjust the command as per your application's start command
    command: npm start

  caddy:
    image: caddy:latest
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
