services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Adjust the command as per your application's start command
    command: npm start
